---
all:
  hosts:
    localhost:
      ansible_connection: local
    # Add your servers here:
    # my-server.example.com:
    #   ansible_user: ubuntu
    #   ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  children:
    local:
      hosts:
        localhost:
    # servers:
    #   hosts:
    #     my-server.example.com:
