---
all:
  hosts:
    localhost:
      ansible_connection: local
    gw.brodie.rocks:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    n8n.yvrbtclabs.dev:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  children:
    local:
      hosts:
        localhost:
    servers:
      hosts:
        gw.brodie.rocks:
        n8n.yvrbtclabs.dev:
